---
title: "ACCEPTANCE TEST"
output:
  html_document:
  df_print: paged
pdf_document: default
code_folding: hide
---

```{r library and authentication, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
### Install Library

# if (!requireNamespace("remotes")) {
#   install.packages("remotes")
# }
# remotes::install_github("ropensci/ruODK@main",
#                         dependencies = TRUE,
#                         force = TRUE)
# install.packages("eeptools") # for calculate age

### Import Library

# library(ruODK)
library(tidyverse)
library(eeptools)
library(ggplot2)

### Import Authentication
source("auth.R")
```

```{r get data, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}

# Create Empty Data
dataRaw <- c()

### Loop Read Data
for (svc in c(svc_afkaaruna, svc_alkarimiyah, svc_inayatullah, svc_maslakulhuda)) {
  ### Setup ruODK
  ruODK::ru_setup(
    svc = svc,
    un = un,
    pw = pw,
    tz = tz,
    verbose = TRUE
  )
  
  # Get data from ODK
  dataODK <-
    ruODK::odata_submission_get(local_dir = fs::path("vignettes/media"))
  
  # Cek dimentional of data
  print(dim(dataODK))
  
  dataRaw <- bind_rows(dataRaw, dataODK)
}

```

```{r preprocessing, echo=FALSE, message=FALSE, warning=FALSE, include=TRUE, paged.print=FALSE}
### Data Preprocessing
data <- dataRaw
colnames(data) <- sub('group_first_page_group_', '', colnames(data)) # rename column name
colnames(data) <- sub('group_second_page_group_', '', colnames(data)) # rename column name

dataName <- c('identitas_name','tracer_name1','tracer_name2','tracer_name3')
data[dataName] <- lapply(data[dataName], str_to_title)  #Change name to TitleCase

```

```{r dob gender, echo=FALSE, message=FALSE, warning=FALSE, include=TRUE, paged.print=FALSE}
### Calculate DOB

data$identitas_birth_date = as.Date(data$identitas_birth_date, format = "%m/%d/%Y")
data$identitas_dob <- age_calc(data$identitas_birth_date, units = "years")

ggplot(data, aes(x = identitas_dob, fill = identitas_gender)) + geom_histogram(bins = 7, position = "dodge")

```

```{r date survey, echo=FALSE, message=FALSE, warning=FALSE, include=TRUE, paged.print=FALSE}
ggplot(data %>% count(identitas_date_survey), aes(x = identitas_date_survey, n)) + 
  geom_line(color="blue")
```




```{r what need to do, echo=FALSE, message=FALSE, warning=FALSE, include=TRUE, paged.print=FALSE}
# Retrieve data from ODK, MERGE ALL (Form) -> Beda ROW
# Adv (Clustering)


```




```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
idxIsolasi <-
  which(
    dataRaw$result_calc7 == "Anda harus masuk/tetap melakukan isolasi diri mandiri selama kurun waktu 14 hari. Pantau kesehatan Anda dengan melakukan penilaian mandiri ini setiap hari selama masa isolasi."
  )

data <- dataRaw[idxIsolasi, ]

dataSymptom <-
  data[, grep(pattern = "symptom_symptom", x = colnames(dataRaw))]
symptomList <- c(
  "Demam",
  "Batuk atau Sakit Tenggorokan",
  "Napas Pendek",
  "Nyeri Otot",
  "Diare",
  "Kehilangan kemampuan mencium bau",
  "Sakit kepala",
  "Mual atau Muntah",
  "Pilek/Hidung Mampet",
  "Nyeri Tenggorokan",
  "Nafsu Makan Turun",
  "Gatal"
)
colnames(dataSymptom) <- symptomList

symptom_per_subject <- apply(dataSymptom[,symptomList],1, function(x){
  paste(names(which(x=="yes")), collapse = ", ")
})

if (length(symptom_per_subject)==0) {
  data <- data %>% select(identitas_date_survey,
                identitas_name,
                identitas_id_respondent,
                identitas_birth_date) %>% 
  mutate(symptom_per_subject) %>% 
  mutate("Rekomendasi")
} else {
  data <- cbind(strtrim(as.character(data$identitas_date_survey),10),
              data$identitas_name,
              data$identitas_id_respondent,
              strtrim(as.character(data$identitas_birth_date),10),
              symptom_per_subject,"Isolasi Diri"
)
}

colnames(data) <- c("Tanggal Periksa","Nama","ID","Tanggal Lahir","Gejala","Rekomendasi")

#"identitas_id_respondent"     
## [10] "identitas_gender"            
## [11] "identitas_birth_date"        
## [12] "identitas_date_survey"
#"result_calc7"
```

```{r echo=FALSE, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
# ${tsvout:tsvfile}
write.table(data, file = "tsvfile", sep = "\t", qmethod = "double", col.names=NA)
```
